version: '3.8'

volumes:
  mdb:

networks:
  mdb_net:
    driver: bridge

##---------------
## MARIADB
##---------------

services:
  mdb:
    image: mariadb:latest
    container_name: mdb
    environment:
      MARIABD_USER: mdbadmin
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - mdb:/var/lib/mysql
    ports: 
      - 3306:3306
    networks:
      - mdb_net 
    
##---------------
## PhpMyAdmin
##---------------
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mdb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8080:80
    networks:
      - mdb_net
    depends_on:
      - mdb
    