##---------------
## Mongo DB
##---------------
version: '3.8'

volumes:
  mongo_vol:

networks:
  mongo_net:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    networks:
      - mongo_net 
    ports: 
    - 27017:27017
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

# #---------------
# # Mongo EXPRESS
# #---------------
  mongo-express:
    image: mongo-express:latest
    networks:
      - mongo_net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret 
