version: '3.8'

volumes:
  mongodb:

networks:
  mongodb_net:
    driver: bridge

##---------------
## Mongo DB
##---------------
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb:/data/db
    ports: 
      - 27017:27017
    networks:
      - mongodb_net 
    
##---------------
## Mongo EXPRESS
##---------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret 
    volumes:
      - mongodb:/data/db
    ports:
      - 8081:8081
    networks:
      - mongodb_net


