##---------------
## Mongo DB
##---------------
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - $HOME/ubuntu/database/mongo_db:/data/db
    ports: 
      - 27017:27017
    networks:
      - mongo_net 
    

##---------------
## Mongo EXPRESS
##---------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret 
    volumes:
      - $HOME/ubuntu/database/mongo_db
    ports:
      - 8081:8081
    networks:
      - mongo_net
    
networks:
  mongo_net:
    driver: bridge
